/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.DangNhapDAO;
import DAO.LichLamViecDAO;
import DAO.PhiGuiXeDAO;
import DTO.INFO_TKNV;
import DTO.PhiDTO;
import DTO.lichlamviec;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Le Chuong
 */
public class PFChinhSuaPhi extends javax.swing.JPanel {
    private String MaNV;

    /**
     * Creates new form PFPhanLich
     */
    public PFChinhSuaPhi(String ma) {
        initComponents();
        MaNV=ma;
        loadTable();
    }

    public void loadTable() {
        ArrayList<PhiDTO> list = PhiGuiXeDAO.loadPhi();
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[6];
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getLoaiXe();
            row[1] = list.get(i).getPhiBanNgay();
            row[2] = list.get(i).getPhiBanDem();
            row[3] = list.get(i).getPhiThang();
            row[4] = list.get(i).getNgayTao();
            row[5] = list.get(i).getMaNV();
            tblModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean checkData(String str) {
        // Kiểm tra xem chuỗi chỉ chứa các chữ số và không có ký tự khác
        return Pattern.matches("\\d+", str);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        btnThemTK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxLoaiXe3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BanDem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbBanNgay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BanNgay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbBanDem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Thang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbThang = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(992, 499));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Phí Gửi Xe");

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Loại xe", "Phí ban ngày", "Phí ban đêm", "Phí tháng", "Ngày tạo", "Mã NV"
            }
        ));
        jScrollPane1.setViewportView(TableNhanVien);

        btnThemTK.setBackground(new java.awt.Color(102, 102, 255));
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTK.setText("Cập Nhật");
        btnThemTK.setBorder(null);
        btnThemTK.setBorderPainted(false);
        btnThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemTK.setFocusPainted(false);
        btnThemTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemTKMouseExited(evt);
            }
        });
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Loại Xe :");

        cbxLoaiXe3.setBackground(new java.awt.Color(102, 102, 255));
        cbxLoaiXe3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLoaiXe3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy", "Xe ô tô" }));
        cbxLoaiXe3.setBorder(null);
        cbxLoaiXe3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxLoaiXe3.setFocusable(false);
        cbxLoaiXe3.setName("cbxLoaiXe"); // NOI18N
        cbxLoaiXe3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaiXe3ItemStateChanged(evt);
            }
        });
        cbxLoaiXe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiXe3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Phí Ban Ngày");

        BanDem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BanDem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanDemMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("VND");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phí Ban Đêm");

        BanNgay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BanNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanNgayMouseClicked(evt);
            }
        });
        BanNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanNgayActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("VND");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Phí Tháng");

        Thang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Thang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThangMouseClicked(evt);
            }
        });
        Thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BanDem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBanDem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(246, 246, 246)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbxLoaiXe3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbBanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxLoaiXe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BanDem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbBanDem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed

         try {
            String p1=BanNgay.getText();
            String p2=BanDem.getText();
            String p3=Thang.getText();
            if (BanNgay.getText().equals("")) {
                lbBanNgay.setText("*Chưa nhập phí ban ngày.");
                lbBanNgay.setForeground(Color.red);
                Border RedLine = BorderFactory.createLineBorder(Color.red);
                BanNgay.setBorder(RedLine);
            }
            else if (BanDem.getText().equals("")) {
                lbBanDem.setText("*Chưa nhập phí ban đêm.");
                lbBanDem.setForeground(Color.red);
                Border RedLine = BorderFactory.createLineBorder(Color.red);
                BanDem.setBorder(RedLine);
            }
            else if (Thang.getText().equals("")) {
                lbThang.setText("*Chưa nhập phí tháng.");
                lbThang.setForeground(Color.red);
                Border RedLine = BorderFactory.createLineBorder(Color.red);
                Thang.setBorder(RedLine);
            }
            else if (!BanNgay.getText().equals("") && !BanDem.getText().equals("") && !Thang.getText().equals("") ) {
                PhiGuiXeDAO pgx = new PhiGuiXeDAO();
                if (checkData(p1)==false){
                    lbBanNgay.setText("*Nhập phí không đúng định dạng");
                    lbBanNgay.setForeground(Color.red);
                    Border RedLine = BorderFactory.createLineBorder(Color.red);
                    BanNgay.setBorder(RedLine);
                }
                else if (checkData(p2)==false){
                    lbBanDem.setText("*Nhập phí không đúng định dạng");
                    lbBanDem.setForeground(Color.red);
                    Border RedLine = BorderFactory.createLineBorder(Color.red);
                    BanDem.setBorder(RedLine);
                }
                else if (checkData(p3)==false){
                    lbThang.setText("*Nhập phí không đúng định dạng");
                    lbThang.setForeground(Color.red);
                    Border RedLine = BorderFactory.createLineBorder(Color.red);
                    Thang.setBorder(RedLine);
                }
                else{
                    PhiDTO phi=new PhiDTO();
                    if (cbxLoaiXe3.getSelectedItem().equals("Xe máy")){
                        phi.setLoaiXe("Xe may");
                    }
                    else phi.setLoaiXe("Xe o to");
                    phi.setPhiBanNgay(Integer.parseInt(p1));
                    phi.setPhiBanDem(Integer.parseInt(p2));
                    phi.setPhiThang(Integer.parseInt(p3));
                    phi.setNgayTao(LocalDate.now());
                    phi.setMaNV(MaNV);
                    if (pgx.capNhatPhi(phi)> 0) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                        BanNgay.setText("");
                        BanDem.setText("");
                        Thang.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật không thành công!");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnThemTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseEntered
        // TODO add your handling code here:
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.BOLD, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnThemTKMouseEntered

    private void btnThemTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemTKMouseExited
        // TODO add your handling code here:
        btnThemTK.setFont(new Font(btnThemTK.getFont().getName(), Font.PLAIN, btnThemTK.getFont().getSize()));
        btnThemTK.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnThemTKMouseExited

    private void cbxLoaiXe3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaiXe3ItemStateChanged

    }//GEN-LAST:event_cbxLoaiXe3ItemStateChanged

    private void cbxLoaiXe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiXe3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiXe3ActionPerformed

    private void BanNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BanNgayActionPerformed

    private void BanNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanNgayMouseClicked
        // TODO add your handling code here:
        lbBanNgay.setText("");
        BanNgay.setBorder(null);
    }//GEN-LAST:event_BanNgayMouseClicked

    private void BanDemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanDemMouseClicked
        // TODO add your handling code here:
        lbBanDem.setText("");
        BanDem.setBorder(null);
    }//GEN-LAST:event_BanDemMouseClicked

    private void ThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThangMouseClicked
        // TODO add your handling code here:
        lbThang.setText("");
        Thang.setBorder(null);
    }//GEN-LAST:event_ThangMouseClicked

    private void ThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BanDem;
    private javax.swing.JTextField BanNgay;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JTextField Thang;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JComboBox cbxLoaiXe;
    private javax.swing.JComboBox cbxLoaiXe1;
    private javax.swing.JComboBox cbxLoaiXe2;
    private javax.swing.JComboBox<String> cbxLoaiXe3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbBanDem;
    private javax.swing.JLabel lbBanNgay;
    private javax.swing.JLabel lbThang;
    // End of variables declaration//GEN-END:variables
}
