/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.DangNhapDAO;
import DTO.AccountDTO;
import DTO.INFO_TKCD;
import DTO.INFO_TKNV;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PFQuanLyCuDan extends javax.swing.JPanel {

    /**
     * Creates new form PFGiveCarBack
     */
    public PFQuanLyCuDan() {
        initComponents();
        setSize(1000, 545);
        //showTable();
        loadTabel();
        //txtPass.setPreferredSize(new Dimension(211, 30));
    }

//    public AccountDTO themAccount() {
//        AccountDTO ac = new AccountDTO();
//        ac.setTaiKhoan(txtTaikhoan.getText());
//        ac.setSdt(txtSdt.getText());
//        //ac.setTrangThai(int(txtTen.getText());
//        ac.setMatKhau(txtPass.getText());
//        return ac;
//    }

//    private void showTable() {
//        DefaultTableModel tblModel;
//        tblModel = new DefaultTableModel();
//        tblModel.setColumnIdentifiers(new String[]{"Tên Nhân Viên", "SDT", "Tài Khoản", "Mật khẩu"});
//        TableNhanVien.setModel(tblModel);
//    }

    public void loadTabel() {
        ArrayList<INFO_TKCD> list = DangNhapDAO.tableInfoCD();
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[6];
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getMaNV();
            row[1] = list.get(i).getHoTen();
            row[2] = list.get(i).getDC();
            row[3] = list.get(i).getCCCD();
            row[4] = list.get(i).getSDT();
            row[5] = list.get(i).getTrangThai();
            tblModel.addRow(row);
        }
    }
    
    public void loadTabel2(INFO_TKCD nx) {
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[6];
        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        row[0] = nx.getMaNV();
        row[1] = nx.getHoTen();
        row[2] = nx.getDC();
        row[3] = nx.getCCCD();
        row[4] = nx.getSDT();
        row[5] = nx.getTrangThai();
        tblModel.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnThemTK = new javax.swing.JButton();
        btnSuaTK = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        btnSuaTK1 = new javax.swing.JButton();
        LamMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1000, 499));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Cư dân");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nhập mã cư dân");

        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã CD", "Họ và Tên", "Địa chỉ", "CCCD", "SDT", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(TableNhanVien);
        if (TableNhanVien.getColumnModel().getColumnCount() > 0) {
            TableNhanVien.getColumnModel().getColumn(0).setResizable(false);
        }

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnThemTK.setBackground(new java.awt.Color(102, 102, 255));
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemTK.setText("Thêm Cư Dân");
        btnThemTK.setBorder(null);
        btnThemTK.setBorderPainted(false);
        btnThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemTK.setFocusPainted(false);
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        btnSuaTK.setBackground(new java.awt.Color(102, 102, 255));
        btnSuaTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaTK.setText("Chỉnh sửa thông tin cư dân");
        btnSuaTK.setBorder(null);
        btnSuaTK.setBorderPainted(false);
        btnSuaTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaTK.setFocusPainted(false);
        btnSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTKActionPerformed(evt);
            }
        });

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimkiem.setForeground(new java.awt.Color(153, 153, 153));
        txtTimkiem.setText("Nhập mã CD...");
        txtTimkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimkiemFocusGained(evt);
            }
        });
        txtTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimkiemMouseClicked(evt);
            }
        });
        txtTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimkiemKeyPressed(evt);
            }
        });

        btnTimkiem.setBackground(new java.awt.Color(102, 102, 255));
        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseClicked(evt);
            }
        });
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnSuaTK1.setBackground(new java.awt.Color(102, 102, 255));
        btnSuaTK1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuaTK1.setText("Quản lí tài khoản");
        btnSuaTK1.setBorder(null);
        btnSuaTK1.setBorderPainted(false);
        btnSuaTK1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaTK1.setFocusPainted(false);
        btnSuaTK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTK1ActionPerformed(evt);
            }
        });

        LamMoi.setBackground(new java.awt.Color(102, 102, 255));
        LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LamMoi.setText("Làm mới");
        LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LamMoiMouseClicked(evt);
            }
        });
        LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnSuaTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimkiem)
                                .addGap(51, 51, 51)
                                .addComponent(LamMoi)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSuaTK1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        new FThemCD().setVisible(true);



//        try {
//            DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
//            String checkacc = txtTaikhoan.getText();
//            if (txtTaikhoan.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập tài khoản!");
//            } else if (txtTen.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhân viên!");
//            } else if (txtSdt.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại!");
//            } else if (txtPass.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!");
//            } else {
//                DangNhapDAO dn = new DangNhapDAO();
//                AccountDTO tk = dn.CheckUser(checkacc);
//                if (tk != null) {
//                    JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!");
//                    txtTaikhoan.setText("");
//                } else {
//                    AccountDTO ac = themAccount();
//                    if (dn.ThemTk(ac) > 0) {
//                        JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
//                        txtTaikhoan.setText("");
//                        txtTen.setText("");
//                        txtSdt.setText("");
//                        txtPass.setText("");
//                        for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
//                            tblModel.removeRow(i);
//                        }
//                        loadTabel();
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại!");
//                    }
//                }
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void txtTimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimkiemFocusGained

    }//GEN-LAST:event_txtTimkiemFocusGained

    private void txtTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimkiemMouseClicked
        txtTimkiem.setText("");
        txtTimkiem.setForeground(Color.black);
    }//GEN-LAST:event_txtTimkiemMouseClicked

    private void txtTimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimkiemKeyPressed
////        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
////            DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
////            Object[] row = new Object[4];
////            String checkAcc = txtTimkiem.getText();
////            DangNhapDAO dn = new DangNhapDAO();
////            AccountDTO ac = dn.CheckUser(txtTimkiem.getText());
////            for (int i = tblModel.getRowCount() - 1; i >= 0; i--) {
////                tblModel.removeRow(i);
////            }
////            if (ac != null) {
////                row[0] = ac.getTenNguoidung();
////                row[1] = ac.getSdt();
////                row[2] = ac.getTaiKhoan();
////                row[3] = ac.getMatKhau();
////                tblModel.addRow(row);
////                TableNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
////                    @Override
////                    public void valueChanged(ListSelectionEvent e) {
////                        if (TableNhanVien.getSelectedRow() >= 0) {
////                            txtTaikhoan.setEditable(false);
////                            txtTen.setText((String) TableNhanVien.getValueAt(TableNhanVien.getSelectedRow(), 0));
////                            txtSdt.setText((String) TableNhanVien.getValueAt(TableNhanVien.getSelectedRow(), 1));
////                            txtTaikhoan.setText((String) TableNhanVien.getValueAt(TableNhanVien.getSelectedRow(), 2));
////                            txtPass.setText((String) TableNhanVien.getValueAt(TableNhanVien.getSelectedRow(), 3));
////                        }
////                    }
////                });
////                txtTimkiem.setText("Nhập tài khoản...");
////                txtTimkiem.setForeground(new Color(153, 153, 153));
////            } else {
////                JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản");
////                txtTimkiem.setText("Nhập tài khoản...");
////                txtTimkiem.setForeground(new Color(153, 153, 153));
////                loadTabel();
////            }
////        }
    }//GEN-LAST:event_txtTimkiemKeyPressed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) TableNhanVien.getModel();
        Object[] row = new Object[6];
        String macd = txtTimkiem.getText();
        DangNhapDAO dn = new DangNhapDAO();
        if (txtTimkiem.getText().contains("Nhập mã CD...") == true) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã cư dân cần tìm");
        } else if (txtTimkiem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã cư dân cần tìm");
            txtTimkiem.setText("Nhập mã CD...");
            txtTimkiem.setForeground(new Color(153, 153, 153));
        } else {
            INFO_TKCD nx=dn.tableInfoCD2(macd);
            if (nx!=null){
                loadTabel2(nx);
            }
            else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy cư dân");
                txtTimkiem.setText("Nhập mã CD...");
                txtTimkiem.setForeground(new Color(153, 153, 153));
                loadTabel();
            }
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTKActionPerformed
        // TODO add your handling code here:
        new FCapNhatCD().setVisible(true);

    }//GEN-LAST:event_btnSuaTKActionPerformed

    private void btnTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseClicked
        // TODO add your handling code here:
        new FQuanLyTKCD().setVisible(true);
    }//GEN-LAST:event_btnTimkiemMouseClicked

    private void btnSuaTK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTK1ActionPerformed
        // TODO add your handling code here:
        new FQuanLyTKCD().setVisible(true);
    }//GEN-LAST:event_btnSuaTK1ActionPerformed

    private void LamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LamMoiMouseClicked

    private void LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiActionPerformed
        // TODO add your handling code here:
        txtTimkiem.setText("Nhập mã CD...");
        txtTimkiem.setForeground(new Color(153, 153, 153));
        loadTabel();
        
    }//GEN-LAST:event_LamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoi;
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton btnSuaTK;
    private javax.swing.JButton btnSuaTK1;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
